name: continualimage
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==0.29.37
      - fasteners==0.15
      - filelock==3.16.1
      - fonttools==4.54.1
      - free-mujoco-py==2.1.6
      - fsspec==2024.10.0
      - glfw==1.12.0
      - idna==3.10
      - imageio==2.35.1
      - importlib-resources==6.4.5
      - jinja2==3.1.4
      - kiwisolver==1.4.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - monotonic==1.6
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.4
      - packaging==24.2
      - pandas==2.0.3
      - pillow==10.4.0
      - pycparser==2.22
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - requests==2.32.3
      - scipy==1.10.0
      - seaborn==0.13.2
      - six==1.16.0
      - sympy==1.13.3
      - torch==2.1.0
      - torchvision==0.16.0
      - tqdm==4.66.1
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - zipp==3.20.2